
<?php echo $this->getwelcome (); ?>

<h1>MY Block</h1>
<form enctype="multipart/form-data" id='my-custom-form'
	action="<?php echo Mage::getUrl("jayblog/index/view")?>" method="post">
	<input type="text" name="title" id="" placeholder='title' /> <br /> <input
		type="text" name="category" id="" placeholder='category' /> <br />
	<!-- 	 <input type="file" name="fileToUpload" id="fileToUpload"> -->
	<br />
	<textarea name="content" id="" cols="30" rows="10"
		placeholder='post content'></textarea>
	<br /> <input type="submit" value="Post" />
</form>

<script type="text/javascript"> <!-- form validation -->
    //< ![CDATA[
        var customForm = new VarienForm('my-custom-form');
    //]]>
</script>

<h2>Posts</h2>
<?php

//  $posts = $this->getPosts ();

// foreach ( $posts as $post ) {
// 	$singlepost = Mage::getModel ( 'jay_blog/myposts' )->load ( $id );
// 	echo $post->getTitle () . '<br />';
// 	echo $post->getPostCategory () . '<br />';
// 	echo $post->getPostContent () . '<br />';
// }

?>
<h2>Products</h2>
<?php
$products = $this->getProducts ( 'entity_id', 1, 5, 10 );
foreach ( $products as $k => $v ) {
	$entity_id = $v->getEntityId ();
	$product = Mage::getModel ( 'catalog/product' )->load ( $entity_id );
	echo $product->getEntityId () . '<br />';
	echo $product->getName () . '<br />';
	echo $product->getDescription () . '<br />';
	echo $product->getPrice () . '<br />';
	echo '<br />**********************************************************<br />';
}

// var_dump($products);

?>





